### ISSUE TITLE
Dependency packages version conflict: prompt_toolkit v3.0.48 (radian v0.6.13) vs prompt_toolkit v3.0.36 (questionary v2.0.1)

### ISSUE THREAD

**Issue by jwoolfolk** [posit-dev/shiny-assistant#5]
Greetings,

I want to apologize for the semi-complexity of the issue I am facing. I have already made an issue post directly to the 'questionary' repo [https://github.com/tmbo/questionary/issues/404] for this, but I thought it might be useful to also make you aware for users who would be utilizing this tool via VSCode and using the popular radian package. 

1. Following the installation procedure for shiny-assistant via cmd prompt: 'pip install -r requirements.txt'.
2. Dependencies for the packages listed include 'questionary' v2.0.1.  
3. A further dependency for 'questionary' is prompt_toolkit.  While following the installation process, it will uninstall prompt_toolkit v3.0.48 and reinstall a deprecated version of prompt_toolkit v3.0.36.
4. This results in a terminal failure within VSCode for R when utilizing the radian package v0.6.13.
5. Return to the cmd prompt: 'pip install --upgrade radian'.
6. Error found:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
questionary 2.0.1 requires prompt_toolkit<=3.0.36,>=2.0, but you have prompt-toolkit 3.0.48 which is incompatible.
7. Run 'pip install --upgrade questionary'.
8. Error found:
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
ipython 8.28.0 requires prompt-toolkit<3.1.0,>=3.0.41, but you have prompt-toolkit 3.0.36 which is incompatible.
radian 0.6.13 requires prompt-toolkit<3.1,>=3.0.41, but you have prompt-toolkit 3.0.36 which is incompatible.

This dependency conflict at the moment eliminates the use of radian within VSCode in order to use the shiny-assistant package.

The easiest solution would obviously be for an update to the 'questionary' dependency version list to include prompt_toolkit v3.0.48. But is there anything that can be done within the shiny-assistant package to directly use prompt_toolkit v3.0.48 and bypass the need for the questionary package?

Thanks for your time!

**Comment by wch** [comment]
questionary isn't a direct dependency of shiny-assistant. It may be coming in indirectly from the `shiny` package.

I think the problem may be fixed when questionary makes a new release -- I think maybe this PR fixes the issue? https://github.com/tmbo/questionary/pull/347 But they have not made a release since then.

I don't think that specifying prompt_toolkit 3.0.48 here would fix the issue. I believe that would still result in a conflict. Perhaps you should encourage the questionary authors to make a new release?
